### ISSUE TITLE
[Feature Request] Ability to close connection

### ISSUE THREAD

**Issue by eXigentCoder** [elasticio/casbin-mongoose-adapter#4]
Firstly thanks for putting this together, works really well!

I'm using the adapter in some tests and the tests fail to exit because the mongodb connection is still open, i'd like a way to call something like `adapter.close()` on the instance.

This would also be useful outside of automated tests to allow for graceful shutdown of an app.

**Comment by ghaiklor** [comment]
Hi, thanks for contribution. I've merged the PR, but I can not publish the package. So, if the change is hot for you, you could install it as a GitHub package.

**Comment by eXigentCoder** [comment]
Thanks, will use the GitHub package for now, will someone else be able publish the update to NPM at some point in the near future?

**Comment by ghaiklor** [comment]
@eXigentCoder I hope so, this package was written by me as part of my contract work with the company. So, the question is to actual owners of this package, I'm just a contributor :)
