### ISSUE TITLE
SavePolicy should be a transaction

### ISSUE THREAD

**Issue by Sefriol** [elasticio/casbin-mongoose-adapter#9]
https://github.com/elasticio/casbin-mongoose-adapter/blob/master/src/adapter.js#L197
General idea of this function is to save whole policy file or nothing. Now it will save part of it if it fails a half way through.

However standard mongoDB multi-document transaction is only supported by replicas and/or shards. I'm not sure whether to fix it by using different outsourced library (mongoose-transaction), just use a try-catch-finally setup to just delete already saved documents or just disable this function if replica / shard is not found.

**Comment by Sefriol** [comment]
Some initial idea here:

https://github.com/Sefriol/casbin-mongoose-adapter/tree/fix-save-policy

**Comment by hsluoyz** [comment]
@ghaiklor  Is this repo still in active maintaining?

**Comment by ghaiklor** [comment]
@hsluoyz I’m no longer a part of elasticio organization, so I can do nothing from my side (no permissions for that). Who is responsible for the repo there I don’t know as well.

Let us assume at this point that repo is not in active maintaining until proved otherwise.

**Comment by hsluoyz** [comment]
@ghaiklor thanks for your explanation. Hope you are doing well in a new place :) BTW, are you still interested in maintaining it personally?

@sefriol I think we can assume this repo is no longer maintained now. I have two options:

1. You maintain this adapter under your account.
2. Put this adapter to Casbin org, you maintain it as a Casbin member.

Please share your points.

**Comment by ghaiklor** [comment]
@hsluoyz yeah, I could take a little time for maintaining it personally. Seems like there is not a much work to do, so I can spare a time for that.

What are your options? Fork the repo and distribute it as non-scoped package? Regard to license, it is possible with copyleft to the original author (in our case, elasticio organization).

**Comment by Sefriol** [comment]
I personally think that all packages related to Casbin should be under the Casbin org. Makes them easier to find and more "trustworthy". Also allows other Casbin members more easily to propose changes to the library.

Since Casbin (and to be fair quite many libraries these days) tend to prefer Typescript, I think this part should also be converted. Though, unlike sequelize-adapter, I would keep the commit history and just do the conversion in same repo.

**Comment by Sefriol** [comment]
Some additional changes I did:

https://github.com/Sefriol/casbin-mongoose-adapter/tree/improve-test-coverage

**Comment by hsluoyz** [comment]
> What are your options? Fork the repo and distribute it as non-scoped package? Regard to license, it is possible with copyleft to the original author (in our case, elasticio organization).

Yeah, I forked it here: https://github.com/node-casbin/mongoose-adapter. We should reveal the original author in the current source code, like by adding the Apache header with elasticio name.

The non-scoped NPM name has already been taken. We should think of another name: https://www.npmjs.com/search?q=casbin-mongoose-adapter

@ghaiklor you are invited to be a Node-Casbin organization member, for your contribution and easy maintenance in future.

@Sefriol you can send PRs to the new repo.

**Comment by ghaiklor** [comment]
@hsluoyz great, in that case, we should move our further discussion there, while this one can be labeled as stale, I believe.

**Comment by hsluoyz** [comment]
Sure
